### DISCUSSION TITLE
Bright/strong colors for high contrast under Annotation

### DISCUSSION THREAD

**Discussion by lindheli** [edrlab/thorium-reader#2846] [Ideas]
Under Annotation, the colors to choose between are all very soft. Would it be possible to add bright/strong colors for higher contrast as well? We also suggest adding black.

**Comment by danielweck** [comment]
CC @JayPanoz (ReadiumCSS wizard / maintainer) and @llemeurfr (EDRLab, Thorium "product owner", ultimately the arbiter of all design decisions / developement priorities) and @HadrienGardeur (also involved in the annotations / colours debate)

Thank you for your suggestion. I think we all absolutely agree on principle that ideally the contrast levels should be consistently high regardless of colour themes (publisher styles and reading app / user overrides), but we made pragmatic implementation choices.

For example the current colour palette was created from a limited set of named colours. Actual hues can vary slightly across RS / Reading Systems, but the symbolic names are to be standardized for interoperability purposes. This is to be proposed as a basis for a revision/update of the W3C annotations specification.

Plus, the availability of colour themes vary from one RS to another. For example Thorium doesn't support Windows-native system-level high-contrast themes yet, but this could be a new variable to adjust for when offering colours for highlights.

Note that highlights are used for annotations, search results, TTS (and to some extent EPUB3 Media Overlays synchronised text-audio too).

So, this is to be discussed further. I am moving this to a GitHub discussion.

**Comment by danielweck** [comment]
Also see: https://github.com/edrlab/thorium-reader/discussions/2817

**Comment by danielweck** [comment]
@lindheli do you have a screenshot of a colour palette that would work for you? (maybe from other reading systems)

**Comment by llemeurfr** [comment]
There are two levels of discussion here. 
1. Our designer chose the initial colour palette after some research. During the discussion on the export/import of annotations, [we decided to limit the possibilities to 6 values](https://github.com/readium/annotations/discussions/7), representing a union of those found in well-known reading systems. Adding more values to this list would be cumbersome for most users. 
2. As Daniel said, we could make so that in certain conditions (= high contrast chosen at system level), these colors (yellow, green, blue ...) appear stronger.  

I like this solution because it does not add any complexity to the user interface, and the UX adapts itself to the context of use of the app.

**Comment by danielweck** [comment]
I noticed that this issue was "locked" by GitHub earlier on, when I attempted to convert this to a "discussion" (GitHub crashed several times in a row, so I gave up in the end ;)

**Comment by danielweck** [comment]
Thank you Linda for sending this in:

"Here is a list of the colors to choose between in EasyReader, which is one of the current readers we recommend for our users, just for reference. This is not necessarily the best list of colors, just what our users are used to."

![Image](https://github.com/user-attachments/assets/adf52a76-fabc-46e4-9b31-89d6419f5cd5)

**Comment by JayPanoz** [comment]
> ideally the contrast levels should be consistently high regardless of colour themes (publisher styles and reading app / user overrides)

As a side note, and I guess we will discuss that during the next engineering call, I‘ve started to give this a look in Playground + ts-toolkit, specifically the high-contrast issue, and there are some interesting problems to solve, or at least multiple strategies to implement with caveats. 

Note CSS now has a [`color-mix()` functional notation](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix) that gives an idea of how complex things can become re. color support.

**Comment by danielweck** [comment]
On this topic:
* https://lea.verou.me/blog/2024/contrast-color/
* https://blackorwhite.lloydk.ca

In Thorium's highlighting engine I attempted to use fancy CSS, but Chromium broke things in very interesting ways (Electron updates, as well as mainstream evergreen Chrome), so I opted for a much simpler contrast ratio calculation:

```css
@supports (color: oklch(from red l c h)) { 
        background-color: rgb(R, G, B);

        color: oklch(from rgb(R, G, B)) clamp(0, (0.7 / l - 1) * infinity, 1) c h);
}
```

```css
@supports (color: oklch(from color-mix(in oklch, red, tan) l c h)) {
        background-color: rgb(R, G, B);

        color: color(from rgb(R, G, B) xyz-d65 clamp(0, (0.36 / y - 1) * infinity, 1) clamp(0, (0.36 / y - 1) * infinity, 1) clamp(0, (0.36 / y - 1) * infinity, 1));
    }
}
```

```css
@supports (color: contrast-color(red)) {
        background-color: rgb(R, G, B);

        color: contrast-color(rgb(R, G, B));
    }
}
```

===>


```js
const calcRGB = (rgb: number) => {
    return (rgb <= 0.03928) ? rgb / 12.92 : ((rgb + 0.055) / 1.055) ** 2.4;
};
const computeHighContrastForegroundColourForBackground = (r: number, g: number, b: number) => {
    let foregroundColour = "#ffffff";
    const red = calcRGB(r);
    const green = calcRGB(g);
    const blue = calcRGB(b);
    // sRGB Luma (ITU Rec. 709) https://en.wikipedia.org/wiki/Rec._709
    const luminance = 0.2126 * red + 0.7152 * green + 0.0722 * blue;
    const pickBlack = (luminance + 0.05) / 0.05;
    const pickWhite = 1.05 / (luminance + 0.05);
    if (pickBlack > pickWhite) {
        foregroundColour = "#000000";
    }
    return foregroundColour;
};
```
