### ISSUE TITLE
Heading tags vs Readium CSS

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1516]
The problem was expressed some weeks ago by an author who does not manage to get the `h3` display not interlines he wants in his cover page. 

```css
    h3 {
	text-indent: 0em;
        font-size: 4em;
        font-weight: bold;
        margin-top: 2.0em;
        margin-bottom: 1.0em;
        text-align: center;
	font-family: Amagro;
	}
```

```html
<body>
  <p>&#160;</p>
<h1 class="nodisplay" title="Title Page">&#160;</h1>
<div class="container">
<h3>Second Law</h3>
<p class="seriestitle">A Speculative Fiction Anthology</p>
<p class="author">Speculative Fiction Writers</p>
<p class="authorsite"><a href="www.specficwriters.com">www.specficwriters.com</a></p>
<p class="publisher">OTI PRESS</p>
</div>
</body>
```

In Thorium

![ThoriumExample](https://user-images.githubusercontent.com/14943186/122445836-3d98ae80-cfa2-11eb-9fdc-94d625572f23.jpeg)

In ADE

![AdobeDigitalEditionsExample](https://user-images.githubusercontent.com/14943186/122445808-32de1980-cfa2-11eb-99f9-da8804e5ccac.jpeg)
