### ISSUE TITLE
Please Post Release Checksums and Key Signatures with Verification Instructions

### ISSUE THREAD

**Issue by uriscoes** [edrlab/thorium-reader#1611]
Hello edrlab team!

I admire your team's efforts to bring an open sourced ebook reader to the market, thank you! I am very impressed by the recent news regarding an epub annotation standard, awesome stuff!

Open source developers should allow their users to verify the integrity and authenticity of the product. This is done by doing the following:

1. Making the code open sourced [Already Done! Good job! :)]

2. Posting checksums of the builds. [I could not find any]

    I could not find checksums of your images. A cryptographic checksum protocol (like SHA-256) allows your users to verify the integrity of their download. 

    **_Please begin posting the SHA-256 checksums for each new release._**

3. Posting key signatures and instructions for verifying the builds. [I could not find any]

    I could not find key signatures for your releases. Cryptographic signatures allow users to verify that the author of the release is genuine. 

    **_Please begin signing new releases and post the signature verification instructions for your users to follow._**
    Here is a quick guide on making signatures: https://gist.github.com/gz-c/de3f9c43343b2f1a27c640fe529b067c
 
Doing these two things is relatively quick and easy, and once accomplished demonstrates your team's professionalism and commitment to your product's integrity and authenticity.

**Thank you very much in advance!**

**Comment by danielweck** [comment]
The sha256 + PGP signature approach is very good (but likely only used by a few very cautious users):

https://library.panic.com/nova/release-integrity/

Note that Thorium's Windows and Mac OS releases are code-signed (and the Apple DMG is notarised)

**Comment by danielweck** [comment]
I checked Thorium's Electron Builder output. The `release/latest-mac.yml` file contains:
```
version: 2.1.0
files:
  - url: Thorium-2.1.0.dmg
    sha512: QLvXfQ3XfobPTyax4JGZaPbC6e+6BgGgaMYqk43vWwCRP2aMg1ZF1sLfc34G//mpw2ryaVRGH4qIrHr1fa+Fdg==
    size: 107019774
path: Thorium-2.1.0.dmg
sha512: QLvXfQ3XfobPTyax4JGZaPbC6e+6BgGgaMYqk43vWwCRP2aMg1ZF1sLfc34G//mpw2ryaVRGH4qIrHr1fa+Fdg==
releaseDate: '2022-08-09T15:57:18.793Z'
```

At the next release, we will provide the checksum info for Mac, Linux and Windows, by copying the details into the release page (e.g. https://github.com/edrlab/thorium-reader/releases/tag/v2.1.0 )
